# 04-external-secret/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: <K8S_SECRET_NAME>
  namespace: <K8S_NAMESPACE>
spec:

  # Fréquence de synchronisation
  # ESO va re-lire AWS Secrets Manager toutes les heures
  # Si le secret change dans AWS, le Kubernetes Secret est mis à jour
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager   # Doit matcher metadata.name du SecretStore
    kind: ClusterSecretStore

  # Le Kubernetes Secret qui sera créé automatiquement
  target:
    name: <K8S_SECRET_NAME>      # Nom du Secret Kubernetes créé
    creationPolicy: Owner        # ESO gère le lifecycle — si ExternalSecret supprimé, Secret supprimé aussi

  # Mapping : quelle clé AWS → quelle clé dans le Secret Kubernetes
  data:
    - secretKey: API_KEY        # Nom de la clé dans le Kubernetes Secret
      remoteRef:
        key: <AWS_SECRET_NAME>      # Nom du secret dans AWS Secrets Manager
        property: API_KEY       # Propriété dans le JSON du secret AWS

    - secretKey: DB_PASSWORD
      remoteRef:
        key: <AWS_SECRET_NAME>
        property: DB_PASSWORD
