apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: <K8S_NAMESPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <APP_NAME>
          image: <CONTAINER_IMAGE>
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: <K8S_SECRET_NAME>
            defaultMode: 0400
